#!/bin/sh

MONGO_CONTAINER_NAME=ammio_mongo

echo -n '• Development enviroment: '
docker stop $MONGO_CONTAINER_NAME > /dev/null 2> /dev/null
docker rm $MONGO_CONTAINER_NAME > /dev/null 2> /dev/null
echo 'cleaned'

read -p '• Remove database data? [y/N] ' yn
if [ "$yn" == "Y" ] || [ "$yn" == "y" ]
then
  echo -n '• Database data: '
  docker volume rm $MONGO_CONTAINER_NAME > /dev/null 2> /dev/null
  echo 'remove'
fi
